### ISSUE TITLE
Migrate to SeleniumHQ 3

### ISSUE THREAD

**Issue by cezarypiatek** [cezarypiatek/Tellurium#11]
1) Update nuget package to Selenium 3
2) Update script for downloading webdrivers (add geckodriver)

**Comment by kmorcinek** [comment]
ad 1. I can update them. When will I be sure that everything works? When the code compiles and the SampleUITest tests are passing?

ad 2. Should it be done similar to #20 ?

**Comment by kmorcinek** [comment]
I have created a bug #21  that covers updating to geckodriver. The are separate think (geckodriver and Selenium 3), so separate issues are better, @cezarypiatek what do you think?

**Comment by cezarypiatek** [comment]
Ad1. I have a private set of tests (over a 300 assertions) When I run this suit and everything will be ok then I'll accept your PR.

Ad2.  Please extend script for downloading drivers. Nuget packages should be an alternative (there is no OFFICIAL nuget package with given driver)

**Comment by cezarypiatek** [comment]
According do geckodriver issue tracker (https://github.com/mozilla/geckodriver/issues) there is a lot issues related to clicking and typing (SenKeys) so I'm still not convinced about migration to Selenium 3.X

**Comment by kmorcinek** [comment]
I fully understand that.

**Comment by cezarypiatek** [comment]
I've created branch  SeleniumHQ_3_5  with Selenium 3.6. There has been introduced two BrowserTypes related to Firefox:
1. BrowserType.Firefox -> Use legacy Firefox Driver for Firefox 47.0.1
2. BrowserType.FirefoxGecko -> Use Geckodriver (marionette)

This is necessary because Geckodriver has issues with clicking what makes impossible to create stable UI tests. It also does not support full page screenshots what makes VisualAssertion useless.
