### ISSUE TITLE
Full page screenshot using Chrome Remote Interface

### ISSUE THREAD

**Issue by metgens** [cezarypiatek/Tellurium#47]
Create fullpage screenshots in Chrome >59 according to this solution implemented in Java:

https://stackoverflow.com/questions/45199076/take-full-page-screen-shot-in-chrome-with-selenium

**Comment by cezarypiatek** [comment]
Thanks for the idea. This approach looks promising. If you have working solution in C# you can create PR. To make it work with Tellurium you should create class that inherits form IBrowserCameraLens interface.

**Comment by metgens** [comment]
I created new class implementing IBrowserCameraLens and also had to create new class ChromeDriverExtended inheriting from ChromeDriver. Don't like inheritance but there was no other way. 

I'm close to a working solution.

**Comment by cezarypiatek** [comment]
@metgens Thanks for collaboration. I'm really appreciate. This is really valuable feature.
