### ISSUE TITLE
What's the relation to this and the old Google Code project?

### ISSUE THREAD

**Issue by jzabroski** [cezarypiatek/Tellurium#64]
https://code.google.com/archive/p/aost/

**Comment by cezarypiatek** [comment]
Yes, I'm aware of this old google project but there's nothing in common. It's just a coincidence. I came up with the name of the project, and then a month later I realized that it collides with this google thing - it was too late to change the name.

**Comment by lukasz-pekala** [comment]
This should be closed IMHO and moved to documentation / Q&A section
